### ISSUE TITLE
[Bug] Tooltip showing wrong item in the sniper list

### ISSUE THREAD

**Issue by zeenk** [Auctionator/PointBlankSniper#19]
Shows as the normal version of the belt but when you go to buy it it shows as mythic
![2022-06-22_21-41-11](https://user-images.githubusercontent.com/68170439/175122868-2d03fc7f-e89a-4c88-a112-b40e23911f83.png)
![2022-06-22_21-42-18](https://user-images.githubusercontent.com/68170439/175122951-8ba6e549-4246-42b8-8744-530e9c905fbd.png)

**Comment by plusmouse** [comment]
That's expected behaviour, the information on which item it specifically is is not available when the search is first made, and as the tooltip indicates, you need to attempt to view more details it to get the specific variant.
![image](https://user-images.githubusercontent.com/60280559/175123303-5a025bbe-b41f-4fe6-85bf-033e50cfda39.png)
