### ISSUE TITLE
[Bug?] The price of items with bid only available does not get updated in the sniper list

### ISSUE THREAD

**Issue by zeenk** [Auctionator/PointBlankSniper#22]
The cloak shows as 1g even if it's at 3.8k currently, not sure if this is a bug or intended but thought might as well mention it to you.

![2022-08-15_18-57-46](https://user-images.githubusercontent.com/68170439/184680563-df3917bd-260c-4164-a2a4-01f61239e1b5.png)

![2022-08-15_18-58-06](https://user-images.githubusercontent.com/68170439/184680576-30baf76b-f395-42b0-98bb-1618108cebc3.png)

**Comment by plusmouse** [comment]
I'd think this is a Blizzard API bug reporting the price as 1g despite the fact that it has since increased to 3880g after being posted. If this happens again can you search up the item in the Blizzard UI and screenshot the item search results, including the cloak, specifically this view
![image](https://user-images.githubusercontent.com/60280559/184961157-cc5ff247-0e06-4259-b2e7-6b5d8fe0bfce.png)
